# maps.py (or at top of import_data.py)
league_map = {
    # Premier League (England)
    "Manchester United": "Premier League",
    "Liverpool": "Premier League",
    "Chelsea": "Premier League",
    "Arsenal": "Premier League",
    "Aston Villa": "Premier League",
    "Man City": "Premier League",
    "Brentford": "Premier League",
    "Tottenham": "Premier League",
    "Brighton": "Premier League",
    "Newcastle": "Premier League",
    "Fulham": "Premier League",
    "Crystal Palace": "Premier League",
    "Everton": "Premier League",
    "Sunderland": "Premier League",
    "West Ham": "Premier League",
    "Wolves": "Premier League",
    "Leeds": "Premier League",
    "Bournemouth": "Premier League",
    "Burnley": "Premier League",
    "Forest": "Premier League",
    
    # La Liga (Spain)
    "Barcelona": "La Liga",
    "Real Madrid": "La Liga",
    "Atletico Madrid": "La Liga",
    "Villarreal": "La Liga",
    "Real Betis": "La Liga",
    "Celta Vigo": "La Liga",
    "Espanyol": "La Liga",
    "Real Sociedad": "La Liga",
    "Getafe": "La Liga",
    "Athletic Bilbao": "La Liga",
    "Osasuna": "La Liga",
    "Valencia": "La Liga",
    "Rayo Vallecano": "La Liga",
    "Sevilla": "La Liga",
    "Girona": "La Liga",
    "Alaves": "La Liga",
    "Elche": "La Liga",
    "Mallorca": "La Liga",
    "Levante": "La Liga",
    "Oviedo": "La Liga",
    
    # Serie A (Italy)
    "Inter": "Serie A",
    "Milan": "Serie A",
    "Napoli": "Serie A",
    "Como": "Serie A",
    "Roma": "Serie A",
    "Juventus": "Serie A",
    "Atalanta": "Serie A",
    "Bologna": "Serie A",
    "Sassuolo": "Serie A",
    "Lazio": "Serie A",
    "Udinese": "Serie A",
    "Parma Calcio": "Serie A",
    "Genoa": "Serie A",
    "Cagliari": "Serie A",
    "Torino": "Serie A",
    "Lecce": "Serie A",
    "Fiorentina": "Serie A",
    "Cremonese": "Serie A",
    "Hellas Verona": "Serie A",
    "Pisa": "Serie A",
    
    # Bundesliga (Germany)
    "Bayern Munich": "Bundesliga",
    "Borussia Dortmund": "Bundesliga",
    "TSG Hoffenheim": "Bundesliga",
    "Stuttgart": "Bundesliga",
    "RB Leipzig": "Bundesliga",
    "Bayer Leverkusen": "Bundesliga",
    "Eintracht Frankfurt": "Bundesliga",
    "SC Freiburg": "Bundesliga",
    "FC Augsburg": "Bundesliga",
    "Hamburger SV": "Bundesliga",
    "Union Berlin": "Bundesliga",
    "Borussia Mönchengladbach": "Bundesliga",
    "Werder Bremen": "Bundesliga",
    "1. FC Cologne": "Bundesliga",
    "Mainz 05": "Bundesliga",
    "FC St. Pauli": "Bundesliga",
    "VfL Wolfsburg": "Bundesliga",
    "1. FC Heidenheim": "Bundesliga",
    
    # Ligue 1 (France)
    "PSG": "Ligue 1",
    "Lens": "Ligue 1",
    "Marseille": "Ligue 1",
    "Lyon": "Ligue 1",
    "Stade Rennais": "Ligue 1",
    "Lille": "Ligue 1",
    "Monaco": "Ligue 1",
    "Strasbourg Alsace": "Ligue 1",
    "Stade Brest 29": "Ligue 1",
    "Lorient": "Ligue 1",
    "Angers": "Ligue 1",
    "Toulouse": "Ligue 1",
    "Paris": "Ligue 1",
    "Le Havre": "Ligue 1",
    "Nice": "Ligue 1",
    "Auxerre": "Ligue 1",
    "Nantes": "Ligue 1",
    "Metz": "Ligue 1",
}

country_map = {
    # Premier League
    "Manchester United": "England",
    "Liverpool": "England",
    "Chelsea": "England",
    "Arsenal": "England",
    "Aston Villa": "England",
    "Manchester City": "England",
    "Brentford": "England",
    "Tottenham": "England",
    "Brighton": "England",
    "Newcastle": "England",
    "Fulham": "England",
    "Crystal Palace": "England",
    "Everton": "England",
    "Sunderland": "England",
    "West Ham": "England",
    "Wolves": "England",
    "Leeds": "England",
    "Bournemouth": "England",
    "Burnley": "England",
    "Forest": "England",
    
    # La Liga
    "Barcelona": "Spain",
    "Real Madrid": "Spain",
    "Atletico Madrid": "Spain",
    "Villarreal": "Spain",
    "Real Betis": "Spain",
    "Celta Vigo": "Spain",
    "Espanyol": "Spain",
    "Real Sociedad": "Spain",
    "Getafe": "Spain",
    "Athletic Bilbao": "Spain",
    "Osasuna": "Spain",
    "Valencia": "Spain",
    "Rayo Vallecano": "Spain",
    "Sevilla": "Spain",
    "Girona": "Spain",
    "Alaves": "Spain",
    "Elche": "Spain",
    "Mallorca": "Spain",
    "Levante": "Spain",
    "Oviedo": "Spain",
    
    # Serie A
    "Inter": "Italy",
    "Milan": "Italy",
    "Napoli": "Italy",
    "Como": "Italy",
    "Roma": "Italy",
    "Juventus": "Italy",
    "Atalanta": "Italy",
    "Bologna": "Italy",
    "Sassuolo": "Italy",
    "Lazio": "Italy",
    "Udinese": "Italy",
    "Parma Calcio": "Italy",
    "Genoa": "Italy",
    "Cagliari": "Italy",
    "Torino": "Italy",
    "Lecce": "Italy",
    "Fiorentina": "Italy",
    "Cremonese": "Italy",
    "Hellas Verona": "Italy",
    "Pisa": "Italy",
    
    # Bundesliga
    "Bayern Munich": "Germany",
    "Borussia Dortmund": "Germany",
    "TSG Hoffenheim": "Germany",
    "Stuttgart": "Germany",
    "RB Leipzig": "Germany",
    "Bayer Leverkusen": "Germany",
    "Eintracht Frankfurt": "Germany",
    "SC Freiburg": "Germany",
    "FC Augsburg": "Germany",
    "Hamburger SV": "Germany",
    "Union Berlin": "Germany",
    "Borussia Mönchengladbach": "Germany",
    "Werder Bremen": "Germany",
    "1. FC Cologne": "Germany",
    "Mainz 05": "Germany",
    "FC St. Pauli": "Germany",
    "VfL Wolfsburg": "Germany",
    "1. FC Heidenheim": "Germany",
    
    # Ligue 1
    "PSG": "France",
    "Lens": "France",
    "Marseille": "France",
    "Lyon": "France",
    "Stade Rennais": "France",
    "Lille": "France",
    "Monaco": "France",
    "Strasbourg Alsace": "France",
    "Stade Brest 29": "France",
    "Lorient": "France",
    "Angers": "France",
    "Toulouse": "France",
    "Paris": "France",
    "Le Havre": "France",
    "Nice": "France",
    "Auxerre": "France",
    "Nantes": "France",
    "Metz": "France",
}