# Generated by Django 5.2.12 on 2026-03-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_match_season_remove_player_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='red_cards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='shots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='yellow_cards',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='stats',
            unique_together={('player', 'match')},
        ),
    ]
